insert into premier_league_teams (team_name) values
('Manchester United FC'),
('Tottenham Hotspur FC'),
('AFC Bournemouth'),
('Aston Villa FC'),
('Leicester City FC'),
('Sunderland AFC'),
('Norwich City FC'),
('Crystal Palace FC'),
('Chelsea FC'),
('Swansea City FC'),
('Everton FC'),
('Watford FC'),
('Arsenal FC'),
('West Ham United FC'),
('Newcastle United FC'),
('Southampton FC'),
('Stoke City FC'),
('Liverpool FC'),
('West Bromwich Albion FC'),
('Manchester City FC')